name: Tests

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: Enable Corepack
      run: |
        corepack enable
        corepack prepare yarn@4.12.0 --activate
        yarn --version

    - uses: calcit-lang/setup-calcit@3b5843cb725963bb4ee158cfe49dad877134963e # v1
      
    - name: Install deps
      run: caps --ci && yarn install --immutable

    - name: Validate Calcit
      run: |
        calcit calcit.cirru edit format
        git diff --exit-code -- calcit.cirru
        yarn check-calcit

    - name: "run native entry"
      run: calcit calcit.cirru

    - name: "test js"
      run: calcit calcit.cirru js && node main.mjs

    - name: "check docs markdown"
      run: bash scripts/check-docs-md.sh
